name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.3
      - name: Transform script
        run: julia --project --color=yes builder.jl
      - name: Release
        with:
          files: build/**
        end:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}